In [8]:
import pandas as pd
import numpy as np
import math
M = np.array([[1,3,5,4,0],
              [3,0,0,4,0],
              [5,1,0,5,1]])
print("-----MA TRẬN BAN ĐẦU-----\n",M)

def matr(A,K,ite,b):
    #khoi tao ma tran W,H                    
    U = A.shape[0] #columns
   
    I = A.shape[1] #rows
    
    print(I)
    W = np.random.randn(U,K)
    H = np.random.randn(K,I)
    for j in range(ite):
        for u in range(U):
            for i in range(I):
                if (A[u,i]>0):
                    r_bav=0
                    for k in range (K):
                        r_bav = r_bav + np.dot(W[u,k],H[k,i]);
                    e = A[u,i] - r_bav
                    for k in range (K):
                        W[u,k] +=  2*b*(e * H[k,i])
                        H[k,i] +=  2*b*(e * W[u,k])             
    return np.dot(W,H)
v = matr(M,2,500, 0.01);

print("-----MA TRẬN DỰ ĐOÁN-----\n",v)
print("----------------------------------------------------")
print("-----MA TRẬN DỰ ĐOÁN LÀM TRÒN-----\n",np.around(v))
                
                 
                       
                            
                         
                   
                            
                    
                    
                            
                 
                       
                           
                              
                
                             
                          
                          
                                    
                                
                                
                                  
        
        


                          
                          
                          
                          
    
    

    

-----MA TRẬN BAN ĐẦU-----
 [[1 3 5 4 0]
 [3 0 0 4 0]
 [5 1 0 5 1]]
5
-----MA TRẬN DỰ ĐOÁN-----
 [[1.         3.         5.         4.         2.01877563]
 [3.         1.53333334 2.69835824 4.         1.20625855]
 [5.         1.         1.93442169 5.         1.        ]]
----------------------------------------------------
-----MA TRẬN DỰ ĐOÁN LÀM TRÒN-----
 [[1. 3. 5. 4. 2.]
 [3. 2. 3. 4. 1.]
 [5. 1. 2. 5. 1.]]
